<?xml version="1.0"?>
<sm:properties xmlns:sm="http://www.utc.fr/ics/scenari/v3/modeling">
	<!--Electre-->
	<sm:property key="enable.electre.api" value="false"/>
	<sm:property key="electre.token.url" value="https://login.electre-ng-horsprod.com/auth/realms/electre/protocol/openid-connect/token"/>
	<sm:property key="electre.notice.url" value="https://api.demo.electre-ng-horsprod.com/notices/ean/"/>
	<sm:property key="electre.user"/>
	<sm:property key="electre.password"/>
	<!--Acapela-->
	<sm:property key="enable.electre.api" value="false"/>
	<sm:property key="acapela.url" value="https://acapela-cloud.com"/>
	<sm:property key="acapela.user"/>
	<sm:property key="acapela.password"/>
</sm:properties>
