<?xml version="1.0"?>
<sm:properties xmlns:sm="http://www.utc.fr/ics/scenari/v3/modeling">
	<sm:property group="webapp" key="webapp.public.url" sortKey="10" value="https://studio-paon.org">
		<sm:description xml:space="preserve">URL publique du serveur</sm:description>
	</sm:property>
	<sm:property group="webapp" key="webapp.code" sortKey="20" value="scenari">
		<sm:description xml:space="preserve">Nom du fichier war généré</sm:description>
	</sm:property>
	<sm:property group="webapp" key="webapp.name" sortKey="25" value="Studio Paon">
		<sm:description xml:space="preserve">Nom du serveur</sm:description>
	</sm:property>
	<sm:property group="webapp" key="webapp.system.url" sortKey="30" value="http://127.0.0.1:8080">
		<sm:description xml:space="preserve">URL locale du serveur</sm:description>
	</sm:property>
	<sm:property group="webapp" key="webapp.work.dir" sortKey="40" value="/var/lib/studio-paon">
		<sm:description xml:space="preserve">Chemin vers les fichiers de données du serveur (ce dossier contiendra un ensemble de répertoire : data, addons, working...)</sm:description>
	</sm:property>
	<sm:property group="webapp" key="webapp.logs.dir" sortKey="50" value="/var/log/studio-paon">
		<sm:description xml:space="preserve">Chemin vers les fichiers de logs du serveur</sm:description>
	</sm:property>
	<!--Mail-->
	<sm:property group="mail" key="mail.smtp.host" sortKey="60">
		<sm:description xml:space="preserve">Host du serveur d'envoi des emails.</sm:description>
	</sm:property>
	<sm:property group="mail" key="mail.from" sortKey="70">
		<sm:description xml:space="preserve">Adresse email utilisée dans le champs from des emails envoyés</sm:description>
	</sm:property>
	<!--ES-->
	<sm:property group="ext" key="app.ext.es.host" sortKey="80" value="http://127.0.0.1:9200">
		<sm:description xml:space="preserve">Host du serveur ElasticSearch</sm:description>
	</sm:property>
	<!--Users-->
	<sm:property group="users" key="user.system.password.digest" sortKey="100">
		<sm:description xml:space="preserve">Gestion des utilisateurs : mot de passe de l'utilisateur "system"
CE MOT DE PASSE DOIT ETRE PERSONNALISE POUR DES QUESTIONS DE SECURITE
Le mot de passe doit être hashé en SHA256, exprimé en base 64 et préfixé de la chaine {SHA 256}
Par exemple, le mot de passe "test" donne "{SHA256}n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=" une fois hashé.
Exemple de commande linux pour générer le hash du mot de passe "test": 
echo -n {SHA256} &amp;&amp; echo -n 'test' | openssl dgst -binary -sha256 | openssl base64</sm:description>
	</sm:property>
	<sm:property group="users" key="user.admin.password.digest" sortKey="110">
		<sm:description xml:space="preserve">Gestion des utilisateurs : mot de passe de l'utilisateur "admin"
CE MOT DE PASSE DOIT ETRE PERSONNALISE POUR DES QUESTIONS DE SECURITE
Le mot de passe doit être hashé en SHA256, exprimé en base 64 et préfixé de la chaine {SHA 256}
Par exemple, le mot de passe "test" donne "{SHA256}n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=" une fois hashé.
Exemple de commande linux pour générer le hash du mot de passe "test": 
echo -n {SHA256} &amp;&amp; echo -n 'test' | openssl dgst -binary -sha256 | openssl base64</sm:description>
	</sm:property>
	<sm:property group="users" key="user.writer.password" sortKey="120" value="">
		<sm:description xml:space="preserve">Gestion des utilisateurs : mot de passe de l'utilisateur "writer"
CE MOT DE PASSE DOIT ETRE PERSONNALISE POUR DES QUESTIONS DE SECURITE
Ce user permet la communication ente les portlets chain et depot.
Il doit être exprimé en clair (pas de hash)</sm:description>
	</sm:property>
	<!-- LDAP-->
	<sm:property group="users" key="user.ldap.disabled" sortKey="130" value="true">
		<sm:description xml:space="preserve">LDAP [boolean]  : active / désactive les fonctions LDAP</sm:description>
	</sm:property>
	<sm:property group="users" key="user.ldap.url" sortKey="140">
		<sm:description xml:space="preserve">LDAP : Url principale (et alternatives) pour la connexion au serveur LDAP. ex: ldap://xxx.xxx.xxx.xxx:xxxx</sm:description>
	</sm:property>
	<sm:property group="users" key="user.ldap.baseNamePattern" sortKey="150" value="ou=people,dc=nodomain">
		<sm:description xml:space="preserve">LDAP : baseName de la recherche</sm:description>
	</sm:property>
	<sm:property group="users" key="user.ldap.searchPattern" sortKey="160" value="(&amp;(objectClass=Person)(|(sn={0})(givenName={0})))">
		<sm:description xml:space="preserve">LDAP : {0} pour le compte d'authentification; {1} pour le mot de passe</sm:description>
	</sm:property>
	<sm:property group="users" key="user.ldap.searchAccount" sortKey="170" value="cn=admin,dc=nodomain">
		<sm:description xml:space="preserve">LDAP : compte pour effectuer la recherche</sm:description>
	</sm:property>
	<sm:property group="users" key="user.ldap.searchPassword" sortKey="180" value="xxx">
		<sm:description xml:space="preserve">LDAP : mot de passe pour effectuer la recherche</sm:description>
	</sm:property>
	<!--Electre-->
	<sm:property group="electre" key="enable.electre.api" sortKey="200" value="true">
		<sm:description xml:space="preserve">Activation de l'API Electre pour la récupération des résumés.</sm:description>
	</sm:property>
	<sm:property group="electre" key="electre.token.url" sortKey="210" value="https://login.electre-ng.com/auth/realms/electre/protocol/openid-connect/token">
		<sm:description xml:space="preserve">URL de fourniture du jeton d'accès à l'API Electre.</sm:description>
	</sm:property>
	<sm:property group="electre" key="electre.notices.url" sortKey="220" value="https://api.electre-ng.com/notices/eans?">
		<sm:description xml:space="preserve">URL d'accès aux notices de l'API Electre.</sm:description>
	</sm:property>
	<sm:property group="electre" key="electre.user" sortKey="230">
		<sm:description xml:space="preserve">Utilisateur de l'API electre.</sm:description>
	</sm:property>
	<sm:property group="electre" key="electre.password" sortKey="240">
		<sm:description xml:space="preserve">Mot de passe de l'API Electre.</sm:description>
	</sm:property>
	<!--Acapela-->
	<sm:property group="acapela" key="enable.acapela.api" sortKey="300" value="true">
		<sm:description xml:space="preserve">Activation de l'API Acapela pour la production des pistes audios.</sm:description>
	</sm:property>
	<sm:property group="acapela" key="acapela.url" sortKey="310" value="https://acapela-cloud.com">
		<sm:description xml:space="preserve">URL d'accès à l'API Acapela</sm:description>
	</sm:property>
	<sm:property group="acapela" key="acapela.user" sortKey="320">
		<sm:description xml:space="preserve">Utilisateur de l'API Acapela</sm:description>
	</sm:property>
	<sm:property group="acapela" key="acapela.password" sortKey="330">
		<sm:description xml:space="preserve">Mot de passe de l'API Acapela</sm:description>
	</sm:property>
</sm:properties>
